---

# TFM-Playbook03
# Este playbook realizará una adquisición de información de un nodo Windows utilizando Dumpit.

- name: Adquirir información del sistema de ficheros en Ubuntu (LiME)
  hosts: windows
  vars:
    memorydumpformat: raw
    ansible_user: "{{ansible_user}}"
    ansible_become_password: "{{ansible_password}}"
  tasks:
   
    - name: Comprobar conexión Windows
      win_ping:
      
    - name: Adquirir memoria de Windows
