---

# TFM-Playbook03
# Este playbook realizar치 una adquisici칩n de informaci칩n de un nodo Windows utilizando Dumpit.

- name: Adquirir informaci칩n del sistema de ficheros en Ubuntu (LiME)
  hosts: ubuntu
  vars:
    memorydumpformat: raw
    ansible_user: "{{user}}"
    ansible_become_password: "{{becomepassword}}"
  tasks:
   
    - name: Adquirir memoria en Windows
