---
# Adquisición de memoria mediante la ejecución de LiME

- name: Añadir la etiqueta horaria a la etiqueta de la evidencia
  set_fact:
    evidencelabel: "{{memorydumpname}}-{{ansible_facts.date_time.iso8601_basic_short}}{{extension}}"

- name: Adquirir memoria
  become: yes
  shell:
    chdir: "{{limedirectory}}"
    cmd: insmod "{{limedirectory}}"/lime.ko path="{{memorydumppath}}/{{evidencelabel}}" format=raw
    
- name: Descargar LiME del kernel
  become: yes
  shell:
    cmd: rmmod lime
    
- name: Añadir el usuario que realiza la adquisición a la ruta de almacenaje
  set_fact:
    userstoragepath: "{{storagepath}}/{{ansible_facts.user_id}}"
    
- name: Envío de la adquisición a la máquina controladora
  fetch:
    src: "{{evidencelabel}}"
    dest: "{{userstoragepath}}"

- name: Eliminar el archivo de la captura en el nodo
  file:
    path: "{{evidencelabel}}"
    state: absent
    
- name: Completar la ruta de almacenaje con el nombre del nodo
  set_fact:
    completestoragepath: "{{userstoragepath}}/{{inventory_hostname}}"
        
- name: Calcular el valor hash de la evidencia en el controlador
  shell:
    cmd: sha256sum "{{completestoragepath}}/{{evidencelabel}}" > "{{completestoragepath}}/{{evidencelabel}}".hash
  delegate_to: localhost
     

