---
# El role dumpmemory se encargará de la adquisición de memoria mediante la ejecución de LiME
# Además, almacenará la evidencia adquirida utilizando la etiqueta que recibirá como parámetro
# y calculará el valor hash que permitirá garantizar la integridad de la misma.

- name: Descargar LiME del kernel
  become: yes
  shell:
    cmd: rmmod lime
  failed_when: false

- name: Adquirir memoria
  become: yes
  shell:
    chdir: "{{limedirectory}}"
    cmd: insmod "{{limedirectory}}"/lime.ko path="{{memorydumppath}}/{{memorydumplabel}}" format=raw
    
- name: Envío de la adquisición al controlador
  fetch:
    src: "{{memorydumplabel}}"
    dest: "{{userstoragepath}}"

- name: Eliminar la captura local
  file:
    path: "{{memorydumplabel}}"
    state: absent
        
- name: Calcular hash de la evidencia
  shell:
    cmd: sha256sum "{{completestoragepath}}/{{memorydumplabel}}" > "{{completestoragepath}}/{{memorydumplabel}}".hash
  delegate_to: localhost
     

