---
# Adquisición de memoria mediante la ejecución de LiME

- name: Añadir hora al etiquetado
  set_fact:
    evidencelabel: "{{memorydumpname}}-{{ansible_facts.date_time.iso8601_basic_short}}{{memorydumpextension}}"

- name: Añadir usuario al etiquetado
  set_fact:
    userstoragepath: "{{storagepath}}/{{ansible_facts.user_id}}"

- name: Añadir nombre del nodo al etiquetado
  set_fact:
    completestoragepath: "{{userstoragepath}}/{{inventory_hostname}}"

- name: Adquirir memoria
  become: yes
  shell:
    chdir: "{{limedirectory}}"
    cmd: insmod "{{limedirectory}}"/lime.ko path="{{memorydumppath}}/{{evidencelabel}}" format=raw
    
- name: Descargar LiME del kernel
  become: yes
  shell:
    cmd: rmmod lime
    
- name: Envío de la adquisición al controlador
  fetch:
    src: "{{evidencelabel}}"
    dest: "{{userstoragepath}}"

- name: Eliminar la captura local
  file:
    path: "{{evidencelabel}}"
    state: absent
        
- name: Calcular hash de la evidencia
  shell:
    cmd: sha256sum "{{completestoragepath}}/{{evidencelabel}}" > "{{completestoragepath}}/{{evidencelabel}}".hash
  delegate_to: localhost
     

