---
# Definición de variables utilizadas para el grupo de nodos "windows"

ansible_connection: winrm
ansible_port: 5986
ansible_winrm_server_cert_validation: ignore
ansible_winrm_scheme: https
ansible_become_method: runas
ansible_become_user: SYSTEM
