---
# El role checklime comprobará la existencia de LiME en el nodo.
# Buscará el directorio LiME en el directorio home del usuario remoto 
# y en caso de no encontrarlo devolverá "0"

- name: Buscar LiME
  find:
    paths: "{{homedirectory}}"
    patterns: "LiME"
    file_type: directory
  register: resultado
      
- name: guardar resultado checklime
  set_fact: 
    checklimeresult: "{{resultado.matched}}"
