---
# El role checklime comprobará la existencia de LiME en el nodo.
# Buscará el directorio LiME en el directorio home del usuario remoto 
# y en caso de no encontrarlo devolverá "0"

- name: Comprobar si LiME está instalado
  find:
    paths: "{{homedirectory}}"
    patterns: "LiME"
    file_type: directory
  register: resultadobusqueda
      
- name: guardar resultado del test de instalación de LiME
  set_fact: 
    encontrado: "{{resultadobusqueda.matched}}"

