---

#Inventario específico para el TFM:
#  Automatización de la Adquisición de Evidencias para el Ánalisis Forense
#En el se incluirán las direcciones de los nodos necesarios para las pruebas.

all:
  hosts:
  children:
    # Grupo de nodos con sistema operativo Ubuntu
    ubuntu:
      hosts:
        10.0.2.10:
