---
# El role installsshwindows se encargará de preparar un nodo Windows para su conexión mediante ssh. 

- name: instalar Win32-OpenSSH service
  win_chocolatey:
    name: openssh
    package_params: /SSHServerFeature
    state: present
    
- name: configurar PowerShell como shell por defecto
  win_regedit:
    path: HKLM:\SOFTWARE\OpenSSH
    name: DefaultShell
    data: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    type: string
    state: present
